version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: chinese_poker
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./api/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/chinese_poker

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3005:80"
    depends_on:
      - api

volumes:
  postgres_data: